# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site                  #网站相关信息
title: changsk's blogs  #网站标题 
subtitle:               #网站副标题
description:            #网站描述
keywords: seeker        #网站关键字
author: changsk         #网站作者
language: zh-CN         #网站使用的语言，这里填zh-CN
timezone: Asia/Shanghai #网站使用的时区，这里默认使用电脑的时区

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com #用于绑定域名, 其他的不需要配置
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory                #目录
source_dir: source        #源文件
public_dir: public        #生成的网页文件
tag_dir: tags             #标签
archive_dir: archives     #归档
category_dir: categories  #分类
code_dir: downloads/code
i18n_dir: :lang           #国际化
skip_render:

# Writing                   #写作                     
new_post_name: :title.md    # File name of new posts #新文章标题
default_layout: post        #默认模板(post page photo draft)
titlecase: false            # Transform title into titlecase  #标题转换成大写
external_link: true         # Open external links in new tab  #新标签页里打开连接
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:                 #语法高亮
  enable: true
  line_number: true        #显示行号
  auto_detect: true        #是否自动检测语言 ，默认为 false
  tab_replace:             #tab 替代设置
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10            #每页显示文章的数量，默认为 10
  order_by: -date         #显示文章的顺序，默认为 -date
  
# Category & Tag                   #分类和标签
default_category: uncategorized    #默认分类
category_map:
tag_map:

# Date / Time format  #日期时间格式
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination                        #分页
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions                        #插件和主题
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment                       #部署, 同时发布在 GitHub 和 GitCafe 上面
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/Tkzccsk/changsk.git
  branch: master
  
#插件，例如生成 RSS 和站点地图的
plugins: hexo-generate-feed
